#!/bin/zsh 
# use mathpix api for math ocr
set -e
if xclip -selection clipboard -t image/png -o > /tmp/equa.png
then
	image=$( base64 -i /tmp/equa.png | tr -d \\n)
else
	echo "Make sure that there is an image in CLIPBOARD"
	exit 1
fi
curl -s -X POST https://api.mathpix.com/v3/latex \
	-H "app_id: $app_id" \
	-H "app_key: $app_key" \
	-H 'Content-Type: application/json' \
	-o .json --data @- <<Config
{ 
	"src": "data:image/jpeg;base64,'$image'", 
	"ocr": ["math", "text"],
	"skip_recrop": true,
	"formats": [
		"latex_simplified",
		"latex_styled",
		"text",
		"text_display"
	 ],
	 "format_options": {
		 "latex_styled": {"transforms": ["rm_spaces"]}
	 }
}
Config
jq '.text' .json  -r | xclip -in -selection clipboard
jq '.' .json
