#!/bin/zsh
# This script should come with file exctractData.js.
# And you should set file path variable `jsfile` manualy
set -e
jsfile="$HOME/Documents/Code/Web/extractData.js"
url=https://www.feizhupan.com
if [[ -z $1 ]]; then
	echo "Usage: 52pansou [search item]"
	if ! read -q "answer?Show Last Result? "; then
		exit
	else
		# Add a new after line read stdin
		echo " "
	fi
else
	curl -G \
		--data-urlencode "keyword=$1" \
		$url/search |
		grep -o "__NUXT__=(function(.*));" >/tmp/script
fi
if [[ -s /tmp/script ]]; then
	echo -n "const api='$url/api';\nlet " | </tmp/script <$jsfile >/tmp/list.mjs && node /tmp/list.mjs
else
	echo "No data returned form api $url"
fi
