#!/bin/zsh
# This script should come with file exctractData.js.
# And you should set file path variable `jsfile` manualy
jsfile="$HOME/Documents/Code/Web/extractData.js"
url=https://www.feizhupan.com
curl -G \
	--data-urlencode "keyword=$1" \
	$url/search |
	grep -o "__NUXT__=(function(.*));" >/tmp/script
echo -n "let " | </tmp/script <$jsfile >/tmp/list.mjs && node /tmp/list.mjs
